### ISSUE TITLE
Nominate This not appearing for Subscriber user role

### ISSUE THREAD

**Issue by clnugent13** [PressForward/pressforward#1223]
I have updated the 'Nominate This' setting in the PressForward User Control preferences, but the tool does not appear when logged in as a subscriber. The screenshot with the purple dashboard is the feed items page header when logged in as an Administrator, and the screenshot with the black dashboard shows the feed items page header when logged in as a Subscriber.

<img width="1139" alt="Image" src="https://github.com/user-attachments/assets/5d765646-06eb-4402-b7f1-322049c7cbb4" />
<img width="1207" alt="Image" src="https://github.com/user-attachments/assets/79632a3e-7b5a-44b1-ba64-931519648451" />

**Comment by boonebgorges** [comment]
Thanks for the report. The 'nominate_this' permission check is working in most places throughout PF, but this one bit of interface - where the 'Nominate This' text is shown on the Feed Items panel - was hidden behind a hardcoded 'edit_posts' (ie Contributor) check. See 883f2e82cf5c435a113a1b45fc00aac4123b5944. This should be fixed by b2ee25a.

**Comment by juliaflanders** [comment]
Thank you, Boone! Do you have a sense of when 5.9.1 will come out? We're planning our training for the guest editors/editors-at-large and this functionality is part of their activities.

**Comment by boonebgorges** [comment]
@juliaflanders Is there a specific date when you need it? I'd planned to do it during the week of July 28, but I can move it up if this is critical for your timeline.

**Comment by juliaflanders** [comment]
That timing sounds fine--thank you so much!

**Comment by boonebgorges** [comment]
Ugh, the problem that never dies. Sorry for the trouble. There were some problems deep in the bowels of PF that made it impossible for certain parts of the non-admin nomination flow to work. I think I've fixed them in version 5.9.3, now available in the wordpress.org repo.

**Comment by clnugent13** [comment]
Thank you! The Nominate This tool now works for users who are 'Contributors.' However, users that are 'Subscribers' still cannot use the tool and receive this message when attempting to use it. 

<img width="719" height="619" alt="Image" src="https://github.com/user-attachments/assets/86eb999a-58e7-4478-b199-860ecdcd699d" />

**Comment by boonebgorges** [comment]
Hm, I'm afraid I'm unable to reproduce this. I guess I'll need you to share more information about your settings, specifically at PressForward > Preferences > User Control. Are you certain that you've set the 'Nominate This' role to 'Subscriber'? See screenshot from my own installation.

<img width="1293" height="850" alt="Image" src="https://github.com/user-attachments/assets/2975ce8a-5100-43b4-a4fa-308ab7838753" />

**Comment by clnugent13** [comment]
These are my user settings by role (attached screenshot). Should I have 'no' selected for Advanced user roles?

<img width="1262" height="801" alt="Image" src="https://github.com/user-attachments/assets/90b752c5-345a-4873-8578-28fce7903fab" />

I have tried logging in as a Subscriber in FireFox and Safari and I encounter the same error (attached) any time I try to use Nominate This.

<img width="723" height="689" alt="Image" src="https://github.com/user-attachments/assets/f6347918-e6a3-4ddc-8931-54cb1027804a" />

**Comment by clnugent13** [comment]
Here is a full screenshot of all the user settings.
