### ISSUE TITLE
Feed Forward does not generate a valid feed

### ISSUE THREAD

**Issue by lmullen** [PressForward/pressforward#601]
Feed Forward does not generate a valid feed. I believe the problem has to do with URLs not being escaped as CDATA, especially URLs that include `&`.

Here is the [W3C validator for the DH Now feed](https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fdigitalhumanitiesnow.org%2F%3Ffeed%3Dfeedforward).

**Comment by AramZS** [comment]
It looks like some of our escaped stuff is triggering the problem. We could not escape it, but some of those escaped characters are themselves invalid characters. Not sure what to do about that. I'll have to look into it.

Another error is that we extend a non-standard namespace, which isn't really an error. 

Looks like one item is showing up twice. That's very odd, we have stuff in place to prevent that. It could be that it is coming in through two different sources, but even then it should be combined.

**Comment by AramZS** [comment]
@lmullen With the latest release of PressForward this should be resolved. Can you please double check that this problem is no longer occurring?

**Comment by lmullen** [comment]
@AramZS I was just using the feed validator on the DH Now website. I don't have my own installation of PressForward. The feed for DH Now still does not validate, but I assume that's because this feature hasn't made it to DH Now yet.

https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fdigitalhumanitiesnow.org%2F%3Ffeed%3Dfeedforward

**Comment by AramZS** [comment]
@lmullen Can we loop back to this once DH Now is up to date?

**Comment by lmullen** [comment]
Sure.

On Mon, Jan 11, 2016 at 1:14 PM, Aram Zucker-Scharff <
notifications@github.com> wrote:

> @lmullen <https://github.com/lmullen> Can we loop back to this once DH
> Now is up to date?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PressForward/pressforward/issues/601#issuecomment-170638563>
> .
>



-- 
Lincoln Mullen, http://lincolnmullen.com
Assistant Professor, Department of History & Art History
George Mason University

**Comment by jccatalano** [comment]
This should be fixed with the latest version of WordPress.
