### ISSUE TITLE
Filtering by "My Starred," "Unread," or "Archived" in Nominated Triggers Fatal Error

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#762]
However, sort by "drafted" seems to work fine.
```
Fatal error: Class 'PF_RSS_Import_Relationship' not found in /srv/www/wordpress-default/wp-content/plugins/pressforward/includes/functions.php on line 956
```

**Comment by AramZS** [comment]
Should now be resolved.

**Comment by regan008** [comment]
My starred no longer throws a fatal error but it isn't pulling up any starred items. Further, the archived and unread functions are still throwing a fatal error (see below).
unread error: 
```
Fatal error: Class 'PF_RSS_Import_Relationship' not found in /srv/www/wordpress-default/wp-content/plugins/pressforward/includes/functions.php on line 909
```
Archived error: 
```
Fatal error: Class 'PF_RSS_Import_Relationship' not found in /srv/www/wordpress-default/wp-content/plugins/pressforward/includes/functions.php on line 890
```

**Comment by AramZS** [comment]
Hey @regan008 - I think I got this licked now. Pull down the latest and take a look.

**Comment by regan008** [comment]
@AramZS Archived and unread work now but starred is still not working. Its not throwing an error. Its just not pulling up any items even though there are starred items in nominated.

Not sure if it helps but here is the console output: 
![screenshot 2016-06-07 13 25 48](https://cloud.githubusercontent.com/assets/4553057/15867919/62b2c364-2cb3-11e6-81c0-b7c1704394a4.png)

**Comment by AramZS** [comment]
@regan008 This seems to be confirmed happening in Nominated. Is it happening for you in All Content too?

**Comment by regan008** [comment]
@AramZS Nope not in all content just in nominated

**Comment by AramZS** [comment]
Hey, can we test star filtering in all contexts? It should be resolved now.
