### ISSUE TITLE
Misformatted Date in PF-API Response

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#835]
@AramZS Just wanted to add this as its own issue so it doesn't get lost because I'm noticing its still happening. 

Here is an example of where I'm seeing it: 
```
"item_wp_date": "Sun, 28 Aug 2016 12:34:18 +0000",
 "date_nominated": "2016-08-29T17:39:50+00:00",
```

**Comment by regan008** [comment]
Related to #807

**Comment by AramZS** [comment]
This should now be resolved with any new items going forward, but won't apply retroactively.

**Comment by regan008** [comment]
I'm still seeing this on my local install. I'm noticing it on the posts endpoint on date and date_gmt. 
![screen shot 2016-10-12 at 1 01 33 pm](https://cloud.githubusercontent.com/assets/4553057/19319719/26ee3c00-907c-11e6-94db-685a428efc54.png)

**Comment by AramZS** [comment]
Those fields are WordPress generated, so we do not have control over them, this issue passes.
