### ISSUE TITLE
Errors in php log on WP 4.4 

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#867]
If I am reading the WP-API documentation correctly, the wp-api should work on WP 4.4 and up. I'm not able to access the api at all on my 4.4 install. Here is the the php log: 

```
[07-Nov-2016 15:48:09 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_registered_meta_keys() in /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/fields/class-wp-rest-meta-fields.php:259
Stack trace:
#0 /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/fields/class-wp-rest-meta-fields.php(311): WP_REST_Meta_Fields->get_registered_fields()
#1 /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/endpoints/class-wp-rest-posts-controller.php(1750): WP_REST_Meta_Fields->get_field_schema()
#2 /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/endpoints/class-wp-rest-controller.php(286): WP_REST_Posts_Controller->get_item_schema()
#3 /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/endpoints/class-wp-rest-controller.php(244): WP_REST_Controller->get_context_param()
#4 /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/endpoints/class-wp-rest-posts-controller.php(1803): WP_REST_Controller->get_collection_params()
#5 /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/endpoints in /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/fields/class-wp-rest-meta-fields.php on line 259
[07-Nov-2016 15:48:33 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_registered_meta_keys() in /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/fields/class-wp-rest-meta-fields.php:259
Stack trace:
#0 /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/fields/class-wp-rest-meta-fields.php(311): WP_REST_Meta_Fields->get_registered_fields()
#1 /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/endpoints/class-wp-rest-posts-controller.php(1750): WP_REST_Meta_Fields->get_field_schema()
#2 /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/endpoints/class-wp-rest-controller.php(286): WP_REST_Posts_Controller->get_item_schema()
#3 /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/endpoints/class-wp-rest-controller.php(244): WP_REST_Controller->get_context_param()
#4 /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/endpoints/class-wp-rest-posts-controller.php(1803): WP_REST_Controller->get_collection_params()
#5 /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/endpoints in /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/fields/class-wp-rest-meta-fields.php on line 259
[07-Nov-2016 15:49:10 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_registered_meta_keys() in /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/fields/class-wp-rest-meta-fields.php:259
Stack trace:
#0 /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/fields/class-wp-rest-meta-fields.php(311): WP_REST_Meta_Fields->get_registered_fields()
#1 /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/endpoints/class-wp-rest-posts-controller.php(1750): WP_REST_Meta_Fields->get_field_schema()
#2 /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/endpoints/class-wp-rest-controller.php(286): WP_REST_Posts_Controller->get_item_schema()
#3 /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/endpoints/class-wp-rest-controller.php(244): WP_REST_Controller->get_context_param()
#4 /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/endpoints/class-wp-rest-posts-controller.php(1803): WP_REST_Controller->get_collection_params()
#5 /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/endpoints in /srv/www/fourpointfour/htdocs/wp-content/plugins/WP-API/lib/fields/class-wp-rest-meta-fields.php on line 259
```

**Comment by regan008** [comment]
This appears to happen on 4.4 whether pf is installed or not so I'm not sure this is an issue with PF

**Comment by regan008** [comment]
The same issue is occurring in WP 4.5 but not on 4.6 (which is why we're just finding this).

**Comment by AramZS** [comment]
Test, should now be resolved in 4.2. Not sure what happened with when PF isn't installed tho... mby another plugin making the same mistake as we are?

**Comment by regan008** [comment]
Yeah I'm still having this happen (on wp 4.5 this time) although it is a slightly different message this time: 
```
[29-Nov-2016 16:12:49 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_registered_meta_keys() in /srv/www/FourPointFive/htdocs/wp-content/plugins/rest-api/lib/fields/class-wp-rest-meta-fields.php:244
Stack trace:
#0 /srv/www/FourPointFive/htdocs/wp-content/plugins/rest-api/lib/fields/class-wp-rest-meta-fields.php(296): WP_REST_Meta_Fields->get_registered_fields()
#1 /srv/www/FourPointFive/htdocs/wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-posts-controller.php(1712): WP_REST_Meta_Fields->get_field_schema()
#2 /srv/www/FourPointFive/htdocs/wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-controller.php(288): WP_REST_Posts_Controller->get_item_schema()
#3 /srv/www/FourPointFive/htdocs/wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-controller.php(246): WP_REST_Controller->get_context_param()
#4 /srv/www/FourPointFive/htdocs/wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-posts-controller.php(1760): WP_REST_Controller->get_collection_params()
#5 /srv/www/FourPointFive/htdocs/wp-content/plugins/rest-api in /srv/www/FourPointFive/htdocs/wp-content/plugins/rest-api/lib/fields/class-wp-rest-meta-fields.php on line 244
```

I don't have any other plugins installed and this happens whether or not pf is installed. Could this be an wp api issue and not a pf api issue? The wp-api website does say that it supports back to 4.4 though

**Comment by AramZS** [comment]
That should be a core function as of 4.6 or provided in the rest api plugin. This issue is only showing up in the log @regan008 ?

**Comment by regan008** [comment]
@AramZS No it isn't. It shows up in the log but it also hinders me from accessing the api page at wp-json

**Comment by AramZS** [comment]
Did some checking. It looks like the latest version of the rest api plugin is only compatible with WP4.6 and up. As such, there's nothing we can do to fix this.
