### ISSUE TITLE
Stats UI is not Populating

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#968]
I think something in the stats UI must have broken. The buttons are not generating any content. Here is what I see in the console: 
```
JQMIGRATE: Migrate is installed, version 1.4.1  load-scripts.php:9:542
unreachable code after return statement[Learn More]  pf-api.js:67:5
Object { children: Array[0] } Object {  } Object { store: Object, storeSubscription: null } undefined  app.js:3680:13
ReferenceError: authorsSet is not defined[Learn More]  app.js:3687:1
hb_test  pf-heartbeat.js:2:2
settings-tools.js loaded.  settings-tools.js:1:1
Waiting for load.  views.js:471:2
PF Quick Edit modifications loaded.  quick-edit.js:12:3
Attaching prompt  admin.php:270:6
100  pf-heartbeat.js:67:2
settings-tools loaded.  settings-tools.js:3:2
#nominate-this  settings-tools.js:24:3
PF Metrics Request  admin.php:127:6
1 XMLDocument  admin.php:275:7
PF Metrics Request  load-scripts.php:75:6
Object { cid: "c4", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object, _pending: false, apiRoot: "http://local.wordpress.test/wp-json/", versionString: "pf/v1", _events: Object }  load-scripts.php:20:9458
nav-tab click.  settings-tools.js:5:3
#stats  settings-tools.js:10:3
PF Valid Posts Page set 1 pf-api.js:117:6
unreachable code after return statement[Learn More]  pf-api.js:67:5
PF Author Page set 1 pf-api.js:44:6
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  kwift.FFWEBEXT.min.js:1:62472
```

**Comment by AramZS** [comment]
This should be fixed now. Please double check

**Comment by AramZS** [comment]
Note: https://github.com/PressForward/pressforward/commit/8cded2dbe8839c85d22b1b2856a735fd392eef37

**Comment by regan008** [comment]
Still not working @AramZS. 

Here is what I am seeing in the console: ```Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  kwift.FFWEBEXT.min.js:1:62472
unreachable code after return statement[Learn More]  pf-api.js:77:5```

**Comment by AramZS** [comment]
@regan008 I can't duplicate this, what browser are you using?

**Comment by regan008** [comment]
I'm in firefox, let me check one more time. Josh was having issues with debug bar causing a conflict so let me disable that and try again.

**Comment by regan008** [comment]
So I'm going to go ahead and close this. The conflict was caused by having permalinks on the site set to plain (i.e. http://local.wordpress.test/?p=123) rather than "pretty" permalinks. Using plain links the api has to be accessed like this: http://local.wordpress.test/index.php?rest_route=/pf/v1/stats/pf_posted.

I'll open a separate issue for this.

**Comment by AramZS** [comment]
I think there is also a Firefox conflict

**Comment by AramZS** [comment]
No, I got it, there is no warning that the WP API is required on sites where it isn't working. Adding text
